version: '2'

volumes:
  traveling_disk:

services:
  traveler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trav
    privileged: true
    image: trav
    ports:
      - 8789:8789
      - 8000:8000
    volumes:
      - traveling_disk:/home/jovyan
